### ISSUE TITLE
README.md link error 404

### ISSUE THREAD

**Issue by EuForisch** [microsoft/data-protection-mapping-project#7]
README.md 
points to https://mkslalom.github.io/standards-mapping/
which results in an error 404.

Full Error message:
>There isn't a GitHub Pages site here.

If you're trying to publish one, [read the full documentation ](https://help.github.com/en/github/working-with-github-pages)to learn how to set up GitHub Pages for your repository, organization, or user account.
<

**Comment by gtomwag** [comment]
this has been fixed, the host url is https://dataprotectionmapping.z21.web.core.windows.net/
